<?php

const MULTIVERSO_LBS_VERSION = '1.0.0';
const MULTIVERSO_LB_LEADERBOARD_TABLE_NAME = 'multiverso_leaderboard_leaderboard';
const MULTIVERSO_LB_ORIGINS_TABLE_NAME = 'multiverso_leaderboard_allowed_origins';
const MULTIVERSO_LB_EXPIRATION_DAYS = 30;
const MULTIVERSO_LB_RATE_LIMIT_SECONDS = 60;
const MULTIVERSO_LB_RATE_LIMIT_REQUESTS = 5;
const MULTIVERSO_LB_CORS_ALLOWED_METHODS = "GET, PATCH, PUT, POST, OPTIONS";
